exclude_paths:
  - 'stuff/**'
  - 'openrem/manage.py'
  - 'openrem/remapp/migrations/**'
  - 'openrem/remapp/static/css/**'
  - 'openrem/remapp/static/fonts/**'
  - 'openrem/remapp/static/img/**'
  - 'openrem/remapp/static/js/django_reverse/**'
  - 'openrem/remapp/static/js/**.min.js'
  - 'openrem/remapp/static/js/bootstrap-datepicker.js'
  - 'openrem/remapp/static/js/datepicker.js'
  - 'openrem/remapp/static/js/npm.js'
  - 'openrem/remapp/static/js/sorttable.js'
  - 'openrem/remapp/tests/**'
