image: python:3.6

pipelines:
  default:  # Standard commits are tested but not deployed
    - step:
        script:
          - mv openrem/openremproject/local_settings.py{.example,}
          - sed -i "s/INFO/DEBUG/g" openrem/openremproject/local_settings.py
          - >-
            sed -i "/ENGINE/c\        'ENGINE': 'django.db.backends.postgresql_psycopg2'," openrem/openremproject/local_settings.py
          - >-
            sed -i "/NAME/c\        'NAME': 'pipelines'," openrem/openremproject/local_settings.py
          - >-
            sed -i "/USER/c\        'USER': 'test_user'," openrem/openremproject/local_settings.py
          - >-
            sed -i "/PASSWORD/c\        'PASSWORD': 'test_user_password'," openrem/openremproject/local_settings.py
          - >-
            sed -i "/HOST/c\        'HOST': 'test_user_password'," openrem/openremproject/local_settings.py
          - mv openrem/openremproject/wsgi.py{.example,}
          - pip install psycopg2-binary
          - pip install -U tox
          - tox -e ci
        services:
          - postgres
definitions:
  services:
    postgres:
      image: postgres

#  branches:
#    develop:  # Commits to the develop branch are tested and deployed to dev.openrem.org on success
#      - step:
#          script:
#            - mv openrem/openremproject/local_settings.py{.example,}
#            - sed -i "s/INFO/DEBUG/g" openrem/openremproject/local_settings.py
#            - mv openrem/openremproject/wsgi.py{.example,}
#            - pip install -U tox
#            - tox -e ci
#            - pip install "fabric < 2"
#            - mkdir -p ~/.ssh
#            - cat deploy_tools/my_known_hosts >> ~/.ssh/known_hosts
#            - (umask  077 ; echo $BB_OPENREM_KEY | base64 --decode > ~/.ssh/id_rsa)
#            - fab deploy:host=deploy@dev.openrem.org
#    '*stage':  # Commits to any branch ending in 'stage' are tested and deployed to testing.openrem.org
#      - step:
#          script:
#            - mv openrem/openremproject/local_settings.py{.example,}
#            - sed -i "s/INFO/DEBUG/g" openrem/openremproject/local_settings.py
#            - mv openrem/openremproject/wsgi.py{.example,}
#            - pip install -U tox
#            - tox -e ci
#            - pip install "fabric < 2"
#            - mkdir -p ~/.ssh
#            - cat deploy_tools/my_known_hosts >> ~/.ssh/known_hosts
#            - (umask  077 ; echo $BB_OPENREM_KEY | base64 --decode > ~/.ssh/id_rsa)
#            - fab deploy:host=deploy@testing.openrem.org
