version: '3.7'

services:
  web:
    build: ./openrem
    command: python /opt/venv/lib/python3.8/site-packages/openrem/manage.py runserver 0.0.0.0:8000
    volumes:
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openrem_user
      - POSTGRES_PASSWORD=openrem_pass
      - POSTGRES_DB=openrem_dev

volumes:
  postgres_data:
  media_volume:
