version: '3.7'

services:
  openrem:
    build:
      context: ./openrem
      dockerfile: Dockerfile.prod
    command: gunicorn openremproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/home/app/openrem/mediafiles
      - static_volume:/home/app/openrem/staticfiles
      - migrations_volume:/home/app/openrem/remapp/migrations
      - type: bind
        source: ./scratch
        target: /scratch
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - broker
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - media_volume:/home/app/openrem/mediafiles
      - static_volume:/home/app/openrem/staticfiles
    ports:
      - 80:80
    depends_on:
      - openrem
  broker:
    image: rabbitmq:3-management-alpine

volumes:
  postgres_data:
  media_volume:
  static_volume:
  migrations_volume:
