version: '3.7'

services:
  openrem:
    build:
      context: ./openrem
      dockerfile: Dockerfile.prod
    command: gunicorn openremproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/home/app/openrem/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
  media_volume:
